Document: youki
Title: Debian youki Manual
Author: <insert document author here>
Abstract: This manual describes what youki is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/youki/youki.sgml.gz

Format: postscript
Files: /usr/share/doc/youki/youki.ps.gz

Format: text
Files: /usr/share/doc/youki/youki.text.gz

Format: HTML
Index: /usr/share/doc/youki/html/index.html
Files: /usr/share/doc/youki/html/*.html
