// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "xsd-artist-info-2.0.hxx"

namespace LastFMArtistInfo
{
  // lfm
  // 

  const lfm::artist_type& lfm::
  artist () const
  {
    return this->artist_.get ();
  }

  lfm::artist_type& lfm::
  artist ()
  {
    return this->artist_.get ();
  }

  void lfm::
  artist (const artist_type& artist)
  {
    this->artist_.set (artist);
  }

  void lfm::
  artist (::std::auto_ptr< artist_type > artist)
  {
    this->artist_.set (artist);
  }

  const lfm::status_type& lfm::
  status () const
  {
    return this->status_.get ();
  }

  lfm::status_type& lfm::
  status ()
  {
    return this->status_.get ();
  }

  void lfm::
  status (const status_type& status)
  {
    this->status_.set (status);
  }

  void lfm::
  status (::std::auto_ptr< status_type > status)
  {
    this->status_.set (status);
  }


  // artist
  // 

  const artist::bio_optional& artist::
  bio () const
  {
    return this->bio_;
  }

  artist::bio_optional& artist::
  bio ()
  {
    return this->bio_;
  }

  void artist::
  bio (const bio_type& bio)
  {
    this->bio_.set (bio);
  }

  void artist::
  bio (const bio_optional& bio)
  {
    this->bio_ = bio;
  }

  void artist::
  bio (::std::auto_ptr< bio_type > bio)
  {
    this->bio_.set (bio);
  }

  const artist::image_sequence& artist::
  image () const
  {
    return this->image_;
  }

  artist::image_sequence& artist::
  image ()
  {
    return this->image_;
  }

  void artist::
  image (const image_sequence& image)
  {
    this->image_ = image;
  }

  const artist::mbid_sequence& artist::
  mbid () const
  {
    return this->mbid_;
  }

  artist::mbid_sequence& artist::
  mbid ()
  {
    return this->mbid_;
  }

  void artist::
  mbid (const mbid_sequence& mbid)
  {
    this->mbid_ = mbid;
  }

  const artist::name_sequence& artist::
  name () const
  {
    return this->name_;
  }

  artist::name_sequence& artist::
  name ()
  {
    return this->name_;
  }

  void artist::
  name (const name_sequence& name)
  {
    this->name_ = name;
  }

  const artist::similar_sequence& artist::
  similar () const
  {
    return this->similar_;
  }

  artist::similar_sequence& artist::
  similar ()
  {
    return this->similar_;
  }

  void artist::
  similar (const similar_sequence& similar)
  {
    this->similar_ = similar;
  }

  const artist::stats_sequence& artist::
  stats () const
  {
    return this->stats_;
  }

  artist::stats_sequence& artist::
  stats ()
  {
    return this->stats_;
  }

  void artist::
  stats (const stats_sequence& stats)
  {
    this->stats_ = stats;
  }

  const artist::streamable_sequence& artist::
  streamable () const
  {
    return this->streamable_;
  }

  artist::streamable_sequence& artist::
  streamable ()
  {
    return this->streamable_;
  }

  void artist::
  streamable (const streamable_sequence& streamable)
  {
    this->streamable_ = streamable;
  }

  const artist::url_sequence& artist::
  url () const
  {
    return this->url_;
  }

  artist::url_sequence& artist::
  url ()
  {
    return this->url_;
  }

  void artist::
  url (const url_sequence& url)
  {
    this->url_ = url;
  }


  // bio
  // 

  const bio::published_type& bio::
  published () const
  {
    return this->published_.get ();
  }

  bio::published_type& bio::
  published ()
  {
    return this->published_.get ();
  }

  void bio::
  published (const published_type& published)
  {
    this->published_.set (published);
  }

  void bio::
  published (::std::auto_ptr< published_type > published)
  {
    this->published_.set (published);
  }

  const bio::summary_type& bio::
  summary () const
  {
    return this->summary_.get ();
  }

  bio::summary_type& bio::
  summary ()
  {
    return this->summary_.get ();
  }

  void bio::
  summary (const summary_type& summary)
  {
    this->summary_.set (summary);
  }

  void bio::
  summary (::std::auto_ptr< summary_type > summary)
  {
    this->summary_.set (summary);
  }

  const bio::content_type& bio::
  content () const
  {
    return this->content_.get ();
  }

  bio::content_type& bio::
  content ()
  {
    return this->content_.get ();
  }

  void bio::
  content (const content_type& content)
  {
    this->content_.set (content);
  }

  void bio::
  content (::std::auto_ptr< content_type > content)
  {
    this->content_.set (content);
  }


  // image
  // 

  const image::size_type& image::
  size () const
  {
    return this->size_.get ();
  }

  image::size_type& image::
  size ()
  {
    return this->size_.get ();
  }

  void image::
  size (const size_type& size)
  {
    this->size_.set (size);
  }

  void image::
  size (::std::auto_ptr< size_type > size)
  {
    this->size_.set (size);
  }


  // similar
  // 

  const similar::artist_sequence& similar::
  artist () const
  {
    return this->artist_;
  }

  similar::artist_sequence& similar::
  artist ()
  {
    return this->artist_;
  }

  void similar::
  artist (const artist_sequence& artist)
  {
    this->artist_ = artist;
  }


  // stats
  // 

  const stats::listeners_type& stats::
  listeners () const
  {
    return this->listeners_.get ();
  }

  stats::listeners_type& stats::
  listeners ()
  {
    return this->listeners_.get ();
  }

  void stats::
  listeners (const listeners_type& listeners)
  {
    this->listeners_.set (listeners);
  }

  const stats::playcount_type& stats::
  playcount () const
  {
    return this->playcount_.get ();
  }

  stats::playcount_type& stats::
  playcount ()
  {
    return this->playcount_.get ();
  }

  void stats::
  playcount (const playcount_type& playcount)
  {
    this->playcount_.set (playcount);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace LastFMArtistInfo
{
  // lfm
  //

  lfm::
  lfm (const artist_type& artist,
       const status_type& status)
  : ::xml_schema::type (),
    artist_ (artist, ::xml_schema::flags (), this),
    status_ (status, ::xml_schema::flags (), this)
  {
  }

  lfm::
  lfm (const lfm& x,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    artist_ (x.artist_, f, this),
    status_ (x.status_, f, this)
  {
  }

  lfm::
  lfm (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    artist_ (f, this),
    status_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void lfm::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // artist
      //
      if (n.name () == "artist" && n.namespace_ () == "")
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        if (!artist_.present ())
        {
          this->artist (r);
          continue;
        }
      }

      break;
    }

    if (!artist_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "artist",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "status" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< status_type > r (
          status_traits::create (i, f, this));

        this->status (r);
        continue;
      }
    }

    if (!status_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "status",
        "");
    }
  }

  lfm* lfm::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new lfm (*this, f, c);
  }

  // artist
  //

  artist::
  artist ()
  : ::xml_schema::type (),
    bio_ (::xml_schema::flags (), this),
    image_ (::xml_schema::flags (), this),
    mbid_ (::xml_schema::flags (), this),
    name_ (::xml_schema::flags (), this),
    similar_ (::xml_schema::flags (), this),
    stats_ (::xml_schema::flags (), this),
    streamable_ (::xml_schema::flags (), this),
    url_ (::xml_schema::flags (), this)
  {
  }

  artist::
  artist (const artist& x,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    bio_ (x.bio_, f, this),
    image_ (x.image_, f, this),
    mbid_ (x.mbid_, f, this),
    name_ (x.name_, f, this),
    similar_ (x.similar_, f, this),
    stats_ (x.stats_, f, this),
    streamable_ (x.streamable_, f, this),
    url_ (x.url_, f, this)
  {
  }

  artist::
  artist (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    bio_ (f, this),
    image_ (f, this),
    mbid_ (f, this),
    name_ (f, this),
    similar_ (f, this),
    stats_ (f, this),
    streamable_ (f, this),
    url_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void artist::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // bio
      //
      if (n.name () == "bio" && n.namespace_ () == "")
      {
        ::std::auto_ptr< bio_type > r (
          bio_traits::create (i, f, this));

        if (!this->bio ())
        {
          this->bio (r);
          continue;
        }
      }

      // image
      //
      if (n.name () == "image" && n.namespace_ () == "")
      {
        ::std::auto_ptr< image_type > r (
          image_traits::create (i, f, this));

        this->image ().push_back (r);
        continue;
      }

      // mbid
      //
      if (n.name () == "mbid" && n.namespace_ () == "")
      {
        ::std::auto_ptr< mbid_type > r (
          mbid_traits::create (i, f, this));

        this->mbid ().push_back (r);
        continue;
      }

      // name
      //
      if (n.name () == "name" && n.namespace_ () == "")
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        this->name ().push_back (r);
        continue;
      }

      // similar
      //
      if (n.name () == "similar" && n.namespace_ () == "")
      {
        ::std::auto_ptr< similar_type > r (
          similar_traits::create (i, f, this));

        this->similar ().push_back (r);
        continue;
      }

      // stats
      //
      if (n.name () == "stats" && n.namespace_ () == "")
      {
        ::std::auto_ptr< stats_type > r (
          stats_traits::create (i, f, this));

        this->stats ().push_back (r);
        continue;
      }

      // streamable
      //
      if (n.name () == "streamable" && n.namespace_ () == "")
      {
        this->streamable ().push_back (streamable_traits::create (i, f, this));
        continue;
      }

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        this->url ().push_back (r);
        continue;
      }

      break;
    }
  }

  artist* artist::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new artist (*this, f, c);
  }

  // bio
  //

  bio::
  bio (const published_type& published,
       const summary_type& summary,
       const content_type& content)
  : ::xml_schema::type (),
    published_ (published, ::xml_schema::flags (), this),
    summary_ (summary, ::xml_schema::flags (), this),
    content_ (content, ::xml_schema::flags (), this)
  {
  }

  bio::
  bio (const bio& x,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    published_ (x.published_, f, this),
    summary_ (x.summary_, f, this),
    content_ (x.content_, f, this)
  {
  }

  bio::
  bio (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    published_ (f, this),
    summary_ (f, this),
    content_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void bio::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // published
      //
      if (n.name () == "published" && n.namespace_ () == "")
      {
        ::std::auto_ptr< published_type > r (
          published_traits::create (i, f, this));

        if (!published_.present ())
        {
          this->published (r);
          continue;
        }
      }

      // summary
      //
      if (n.name () == "summary" && n.namespace_ () == "")
      {
        ::std::auto_ptr< summary_type > r (
          summary_traits::create (i, f, this));

        if (!summary_.present ())
        {
          this->summary (r);
          continue;
        }
      }

      // content
      //
      if (n.name () == "content" && n.namespace_ () == "")
      {
        ::std::auto_ptr< content_type > r (
          content_traits::create (i, f, this));

        if (!content_.present ())
        {
          this->content (r);
          continue;
        }
      }

      break;
    }

    if (!published_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "published",
        "");
    }

    if (!summary_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "summary",
        "");
    }

    if (!content_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "content",
        "");
    }
  }

  bio* bio::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new bio (*this, f, c);
  }

  // image
  //

  image::
  image (const ::xml_schema::uri& anyURI,
         const size_type& size)
  : ::xml_schema::uri (anyURI),
    size_ (size, ::xml_schema::flags (), this)
  {
  }

  image::
  image (const image& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::uri (x, f, c),
    size_ (x.size_, f, this)
  {
  }

  image::
  image (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::uri (e, f | ::xml_schema::flags::base, c),
    size_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void image::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "size" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< size_type > r (
          size_traits::create (i, f, this));

        this->size (r);
        continue;
      }
    }

    if (!size_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "size",
        "");
    }
  }

  image* image::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new image (*this, f, c);
  }

  // similar
  //

  similar::
  similar ()
  : ::xml_schema::type (),
    artist_ (::xml_schema::flags (), this)
  {
  }

  similar::
  similar (const similar& x,
           ::xml_schema::flags f,
           ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    artist_ (x.artist_, f, this)
  {
  }

  similar::
  similar (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    artist_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void similar::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // artist
      //
      if (n.name () == "artist" && n.namespace_ () == "")
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        this->artist ().push_back (r);
        continue;
      }

      break;
    }
  }

  similar* similar::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new similar (*this, f, c);
  }

  // stats
  //

  stats::
  stats (const listeners_type& listeners,
         const playcount_type& playcount)
  : ::xml_schema::type (),
    listeners_ (listeners, ::xml_schema::flags (), this),
    playcount_ (playcount, ::xml_schema::flags (), this)
  {
  }

  stats::
  stats (const stats& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    listeners_ (x.listeners_, f, this),
    playcount_ (x.playcount_, f, this)
  {
  }

  stats::
  stats (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    listeners_ (f, this),
    playcount_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void stats::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // listeners
      //
      if (n.name () == "listeners" && n.namespace_ () == "")
      {
        if (!listeners_.present ())
        {
          this->listeners (listeners_traits::create (i, f, this));
          continue;
        }
      }

      // playcount
      //
      if (n.name () == "playcount" && n.namespace_ () == "")
      {
        if (!playcount_.present ())
        {
          this->playcount (playcount_traits::create (i, f, this));
          continue;
        }
      }

      break;
    }

    if (!listeners_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "listeners",
        "");
    }

    if (!playcount_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "playcount",
        "");
    }
  }

  stats* stats::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new stats (*this, f, c);
  }
}

#include <istream>
#include <xercesc/framework/Wrapper4InputSource.hpp>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace LastFMArtistInfo
{
  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMArtistInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
      ::LastFMArtistInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (const ::xercesc::DOMDocument& d,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
        ::LastFMArtistInfo::lfm_ (
          c.get (), f | ::xml_schema::flags::own_dom, p));

      c.release ();
      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "lfm" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
        ::xsd::cxx::tree::traits< ::LastFMArtistInfo::lfm, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "lfm",
      "");
  }

  ::std::auto_ptr< ::LastFMArtistInfo::lfm >
  lfm_ (::xercesc::DOMDocument* d,
        ::xml_schema::flags f,
        const ::xml_schema::properties&)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    const ::xercesc::DOMElement& e (
      c.get ()
      ? *c->getDocumentElement ()
      : *d->getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "lfm" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::LastFMArtistInfo::lfm > r (
        ::xsd::cxx::tree::traits< ::LastFMArtistInfo::lfm, char >::create (
          e, f, 0));
      c.release ();
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "lfm",
      "");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

