// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "xsd-album-info-2.0.hxx"

namespace LastFMAlbumInfo
{
  // lfm
  // 

  const lfm::album_type& lfm::
  album () const
  {
    return this->album_.get ();
  }

  lfm::album_type& lfm::
  album ()
  {
    return this->album_.get ();
  }

  void lfm::
  album (const album_type& album)
  {
    this->album_.set (album);
  }

  void lfm::
  album (::std::auto_ptr< album_type > album)
  {
    this->album_.set (album);
  }

  const lfm::status_optional& lfm::
  status () const
  {
    return this->status_;
  }

  lfm::status_optional& lfm::
  status ()
  {
    return this->status_;
  }

  void lfm::
  status (const status_type& status)
  {
    this->status_.set (status);
  }

  void lfm::
  status (const status_optional& status)
  {
    this->status_ = status;
  }

  void lfm::
  status (::std::auto_ptr< status_type > status)
  {
    this->status_.set (status);
  }


  // album
  // 

  const album::name_type& album::
  name () const
  {
    return this->name_.get ();
  }

  album::name_type& album::
  name ()
  {
    return this->name_.get ();
  }

  void album::
  name (const name_type& name)
  {
    this->name_.set (name);
  }

  void album::
  name (::std::auto_ptr< name_type > name)
  {
    this->name_.set (name);
  }

  const album::artist_type& album::
  artist () const
  {
    return this->artist_.get ();
  }

  album::artist_type& album::
  artist ()
  {
    return this->artist_.get ();
  }

  void album::
  artist (const artist_type& artist)
  {
    this->artist_.set (artist);
  }

  void album::
  artist (::std::auto_ptr< artist_type > artist)
  {
    this->artist_.set (artist);
  }

  const album::id_type& album::
  id () const
  {
    return this->id_.get ();
  }

  album::id_type& album::
  id ()
  {
    return this->id_.get ();
  }

  void album::
  id (const id_type& id)
  {
    this->id_.set (id);
  }

  const album::mbid_type& album::
  mbid () const
  {
    return this->mbid_.get ();
  }

  album::mbid_type& album::
  mbid ()
  {
    return this->mbid_.get ();
  }

  void album::
  mbid (const mbid_type& mbid)
  {
    this->mbid_.set (mbid);
  }

  void album::
  mbid (::std::auto_ptr< mbid_type > mbid)
  {
    this->mbid_.set (mbid);
  }

  const album::url_type& album::
  url () const
  {
    return this->url_.get ();
  }

  album::url_type& album::
  url ()
  {
    return this->url_.get ();
  }

  void album::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void album::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }

  const album::releasedate_type& album::
  releasedate () const
  {
    return this->releasedate_.get ();
  }

  album::releasedate_type& album::
  releasedate ()
  {
    return this->releasedate_.get ();
  }

  void album::
  releasedate (const releasedate_type& releasedate)
  {
    this->releasedate_.set (releasedate);
  }

  void album::
  releasedate (::std::auto_ptr< releasedate_type > releasedate)
  {
    this->releasedate_.set (releasedate);
  }

  const album::image_sequence& album::
  image () const
  {
    return this->image_;
  }

  album::image_sequence& album::
  image ()
  {
    return this->image_;
  }

  void album::
  image (const image_sequence& image)
  {
    this->image_ = image;
  }

  const album::listeners_type& album::
  listeners () const
  {
    return this->listeners_.get ();
  }

  album::listeners_type& album::
  listeners ()
  {
    return this->listeners_.get ();
  }

  void album::
  listeners (const listeners_type& listeners)
  {
    this->listeners_.set (listeners);
  }

  const album::playcount_type& album::
  playcount () const
  {
    return this->playcount_.get ();
  }

  album::playcount_type& album::
  playcount ()
  {
    return this->playcount_.get ();
  }

  void album::
  playcount (const playcount_type& playcount)
  {
    this->playcount_.set (playcount);
  }

  const album::tracks_type& album::
  tracks () const
  {
    return this->tracks_.get ();
  }

  album::tracks_type& album::
  tracks ()
  {
    return this->tracks_.get ();
  }

  void album::
  tracks (const tracks_type& tracks)
  {
    this->tracks_.set (tracks);
  }

  void album::
  tracks (::std::auto_ptr< tracks_type > tracks)
  {
    this->tracks_.set (tracks);
  }

  const album::toptags_type& album::
  toptags () const
  {
    return this->toptags_.get ();
  }

  album::toptags_type& album::
  toptags ()
  {
    return this->toptags_.get ();
  }

  void album::
  toptags (const toptags_type& toptags)
  {
    this->toptags_.set (toptags);
  }

  void album::
  toptags (::std::auto_ptr< toptags_type > toptags)
  {
    this->toptags_.set (toptags);
  }

  const album::wiki_type& album::
  wiki () const
  {
    return this->wiki_.get ();
  }

  album::wiki_type& album::
  wiki ()
  {
    return this->wiki_.get ();
  }

  void album::
  wiki (const wiki_type& wiki)
  {
    this->wiki_.set (wiki);
  }

  void album::
  wiki (::std::auto_ptr< wiki_type > wiki)
  {
    this->wiki_.set (wiki);
  }


  // image
  // 

  const image::size_optional& image::
  size () const
  {
    return this->size_;
  }

  image::size_optional& image::
  size ()
  {
    return this->size_;
  }

  void image::
  size (const size_type& size)
  {
    this->size_.set (size);
  }

  void image::
  size (const size_optional& size)
  {
    this->size_ = size;
  }

  void image::
  size (::std::auto_ptr< size_type > size)
  {
    this->size_.set (size);
  }


  // tracks
  // 

  const tracks::track_sequence& tracks::
  track () const
  {
    return this->track_;
  }

  tracks::track_sequence& tracks::
  track ()
  {
    return this->track_;
  }

  void tracks::
  track (const track_sequence& track)
  {
    this->track_ = track;
  }


  // toptags
  // 

  const toptags::tag_sequence& toptags::
  tag () const
  {
    return this->tag_;
  }

  toptags::tag_sequence& toptags::
  tag ()
  {
    return this->tag_;
  }

  void toptags::
  tag (const tag_sequence& tag)
  {
    this->tag_ = tag;
  }


  // wiki
  // 

  const wiki::published_type& wiki::
  published () const
  {
    return this->published_.get ();
  }

  wiki::published_type& wiki::
  published ()
  {
    return this->published_.get ();
  }

  void wiki::
  published (const published_type& published)
  {
    this->published_.set (published);
  }

  void wiki::
  published (::std::auto_ptr< published_type > published)
  {
    this->published_.set (published);
  }

  const wiki::summary_type& wiki::
  summary () const
  {
    return this->summary_.get ();
  }

  wiki::summary_type& wiki::
  summary ()
  {
    return this->summary_.get ();
  }

  void wiki::
  summary (const summary_type& summary)
  {
    this->summary_.set (summary);
  }

  void wiki::
  summary (::std::auto_ptr< summary_type > summary)
  {
    this->summary_.set (summary);
  }

  const wiki::content_type& wiki::
  content () const
  {
    return this->content_.get ();
  }

  wiki::content_type& wiki::
  content ()
  {
    return this->content_.get ();
  }

  void wiki::
  content (const content_type& content)
  {
    this->content_.set (content);
  }

  void wiki::
  content (::std::auto_ptr< content_type > content)
  {
    this->content_.set (content);
  }


  // track
  // 

  const track::name_type& track::
  name () const
  {
    return this->name_.get ();
  }

  track::name_type& track::
  name ()
  {
    return this->name_.get ();
  }

  void track::
  name (const name_type& name)
  {
    this->name_.set (name);
  }

  void track::
  name (::std::auto_ptr< name_type > name)
  {
    this->name_.set (name);
  }

  const track::duration_type& track::
  duration () const
  {
    return this->duration_.get ();
  }

  track::duration_type& track::
  duration ()
  {
    return this->duration_.get ();
  }

  void track::
  duration (const duration_type& duration)
  {
    this->duration_.set (duration);
  }

  const track::mbid_type& track::
  mbid () const
  {
    return this->mbid_.get ();
  }

  track::mbid_type& track::
  mbid ()
  {
    return this->mbid_.get ();
  }

  void track::
  mbid (const mbid_type& mbid)
  {
    this->mbid_.set (mbid);
  }

  void track::
  mbid (::std::auto_ptr< mbid_type > mbid)
  {
    this->mbid_.set (mbid);
  }

  const track::url_type& track::
  url () const
  {
    return this->url_.get ();
  }

  track::url_type& track::
  url ()
  {
    return this->url_.get ();
  }

  void track::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void track::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }

  const track::streamable_type& track::
  streamable () const
  {
    return this->streamable_.get ();
  }

  track::streamable_type& track::
  streamable ()
  {
    return this->streamable_.get ();
  }

  void track::
  streamable (const streamable_type& streamable)
  {
    this->streamable_.set (streamable);
  }

  void track::
  streamable (::std::auto_ptr< streamable_type > streamable)
  {
    this->streamable_.set (streamable);
  }

  const track::artist_type& track::
  artist () const
  {
    return this->artist_.get ();
  }

  track::artist_type& track::
  artist ()
  {
    return this->artist_.get ();
  }

  void track::
  artist (const artist_type& artist)
  {
    this->artist_.set (artist);
  }

  void track::
  artist (::std::auto_ptr< artist_type > artist)
  {
    this->artist_.set (artist);
  }

  const track::rank_optional& track::
  rank () const
  {
    return this->rank_;
  }

  track::rank_optional& track::
  rank ()
  {
    return this->rank_;
  }

  void track::
  rank (const rank_type& rank)
  {
    this->rank_.set (rank);
  }

  void track::
  rank (const rank_optional& rank)
  {
    this->rank_ = rank;
  }


  // tag
  // 

  const tag::name_type& tag::
  name () const
  {
    return this->name_.get ();
  }

  tag::name_type& tag::
  name ()
  {
    return this->name_.get ();
  }

  void tag::
  name (const name_type& name)
  {
    this->name_.set (name);
  }

  void tag::
  name (::std::auto_ptr< name_type > name)
  {
    this->name_.set (name);
  }

  const tag::url_type& tag::
  url () const
  {
    return this->url_.get ();
  }

  tag::url_type& tag::
  url ()
  {
    return this->url_.get ();
  }

  void tag::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void tag::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }


  // streamable
  // 

  const streamable::fulltrack_optional& streamable::
  fulltrack () const
  {
    return this->fulltrack_;
  }

  streamable::fulltrack_optional& streamable::
  fulltrack ()
  {
    return this->fulltrack_;
  }

  void streamable::
  fulltrack (const fulltrack_type& fulltrack)
  {
    this->fulltrack_.set (fulltrack);
  }

  void streamable::
  fulltrack (const fulltrack_optional& fulltrack)
  {
    this->fulltrack_ = fulltrack;
  }


  // artist
  // 

  const artist::name_type& artist::
  name () const
  {
    return this->name_.get ();
  }

  artist::name_type& artist::
  name ()
  {
    return this->name_.get ();
  }

  void artist::
  name (const name_type& name)
  {
    this->name_.set (name);
  }

  void artist::
  name (::std::auto_ptr< name_type > name)
  {
    this->name_.set (name);
  }

  const artist::mbid_type& artist::
  mbid () const
  {
    return this->mbid_.get ();
  }

  artist::mbid_type& artist::
  mbid ()
  {
    return this->mbid_.get ();
  }

  void artist::
  mbid (const mbid_type& mbid)
  {
    this->mbid_.set (mbid);
  }

  void artist::
  mbid (::std::auto_ptr< mbid_type > mbid)
  {
    this->mbid_.set (mbid);
  }

  const artist::url_type& artist::
  url () const
  {
    return this->url_.get ();
  }

  artist::url_type& artist::
  url ()
  {
    return this->url_.get ();
  }

  void artist::
  url (const url_type& url)
  {
    this->url_.set (url);
  }

  void artist::
  url (::std::auto_ptr< url_type > url)
  {
    this->url_.set (url);
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace LastFMAlbumInfo
{
  // lfm
  //

  lfm::
  lfm (const album_type& album)
  : ::xml_schema::type (),
    album_ (album, ::xml_schema::flags (), this),
    status_ (::xml_schema::flags (), this)
  {
  }

  lfm::
  lfm (const lfm& x,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    album_ (x.album_, f, this),
    status_ (x.status_, f, this)
  {
  }

  lfm::
  lfm (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    album_ (f, this),
    status_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void lfm::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // album
      //
      if (n.name () == "album" && n.namespace_ () == "")
      {
        ::std::auto_ptr< album_type > r (
          album_traits::create (i, f, this));

        if (!album_.present ())
        {
          this->album (r);
          continue;
        }
      }

      break;
    }

    if (!album_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "album",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "status" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< status_type > r (
          status_traits::create (i, f, this));

        this->status (r);
        continue;
      }
    }
  }

  lfm* lfm::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new lfm (*this, f, c);
  }

  // album
  //

  album::
  album (const name_type& name,
         const artist_type& artist,
         const id_type& id,
         const mbid_type& mbid,
         const url_type& url,
         const releasedate_type& releasedate,
         const listeners_type& listeners,
         const playcount_type& playcount,
         const tracks_type& tracks,
         const toptags_type& toptags,
         const wiki_type& wiki)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    artist_ (artist, ::xml_schema::flags (), this),
    id_ (id, ::xml_schema::flags (), this),
    mbid_ (mbid, ::xml_schema::flags (), this),
    url_ (url, ::xml_schema::flags (), this),
    releasedate_ (releasedate, ::xml_schema::flags (), this),
    image_ (::xml_schema::flags (), this),
    listeners_ (listeners, ::xml_schema::flags (), this),
    playcount_ (playcount, ::xml_schema::flags (), this),
    tracks_ (tracks, ::xml_schema::flags (), this),
    toptags_ (toptags, ::xml_schema::flags (), this),
    wiki_ (wiki, ::xml_schema::flags (), this)
  {
  }

  album::
  album (const album& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    artist_ (x.artist_, f, this),
    id_ (x.id_, f, this),
    mbid_ (x.mbid_, f, this),
    url_ (x.url_, f, this),
    releasedate_ (x.releasedate_, f, this),
    image_ (x.image_, f, this),
    listeners_ (x.listeners_, f, this),
    playcount_ (x.playcount_, f, this),
    tracks_ (x.tracks_, f, this),
    toptags_ (x.toptags_, f, this),
    wiki_ (x.wiki_, f, this)
  {
  }

  album::
  album (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    artist_ (f, this),
    id_ (f, this),
    mbid_ (f, this),
    url_ (f, this),
    releasedate_ (f, this),
    image_ (f, this),
    listeners_ (f, this),
    playcount_ (f, this),
    tracks_ (f, this),
    toptags_ (f, this),
    wiki_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void album::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ () == "")
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // artist
      //
      if (n.name () == "artist" && n.namespace_ () == "")
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        if (!artist_.present ())
        {
          this->artist (r);
          continue;
        }
      }

      // id
      //
      if (n.name () == "id" && n.namespace_ () == "")
      {
        if (!id_.present ())
        {
          this->id (id_traits::create (i, f, this));
          continue;
        }
      }

      // mbid
      //
      if (n.name () == "mbid" && n.namespace_ () == "")
      {
        ::std::auto_ptr< mbid_type > r (
          mbid_traits::create (i, f, this));

        if (!mbid_.present ())
        {
          this->mbid (r);
          continue;
        }
      }

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      // releasedate
      //
      if (n.name () == "releasedate" && n.namespace_ () == "")
      {
        ::std::auto_ptr< releasedate_type > r (
          releasedate_traits::create (i, f, this));

        if (!releasedate_.present ())
        {
          this->releasedate (r);
          continue;
        }
      }

      // image
      //
      if (n.name () == "image" && n.namespace_ () == "")
      {
        ::std::auto_ptr< image_type > r (
          image_traits::create (i, f, this));

        this->image ().push_back (r);
        continue;
      }

      // listeners
      //
      if (n.name () == "listeners" && n.namespace_ () == "")
      {
        if (!listeners_.present ())
        {
          this->listeners (listeners_traits::create (i, f, this));
          continue;
        }
      }

      // playcount
      //
      if (n.name () == "playcount" && n.namespace_ () == "")
      {
        if (!playcount_.present ())
        {
          this->playcount (playcount_traits::create (i, f, this));
          continue;
        }
      }

      // tracks
      //
      if (n.name () == "tracks" && n.namespace_ () == "")
      {
        ::std::auto_ptr< tracks_type > r (
          tracks_traits::create (i, f, this));

        if (!tracks_.present ())
        {
          this->tracks (r);
          continue;
        }
      }

      // toptags
      //
      if (n.name () == "toptags" && n.namespace_ () == "")
      {
        ::std::auto_ptr< toptags_type > r (
          toptags_traits::create (i, f, this));

        if (!toptags_.present ())
        {
          this->toptags (r);
          continue;
        }
      }

      // wiki
      //
      if (n.name () == "wiki" && n.namespace_ () == "")
      {
        ::std::auto_ptr< wiki_type > r (
          wiki_traits::create (i, f, this));

        if (!wiki_.present ())
        {
          this->wiki (r);
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    if (!artist_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "artist",
        "");
    }

    if (!id_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "id",
        "");
    }

    if (!mbid_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mbid",
        "");
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "");
    }

    if (!releasedate_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "releasedate",
        "");
    }

    if (!listeners_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "listeners",
        "");
    }

    if (!playcount_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "playcount",
        "");
    }

    if (!tracks_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "tracks",
        "");
    }

    if (!toptags_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "toptags",
        "");
    }

    if (!wiki_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "wiki",
        "");
    }
  }

  album* album::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new album (*this, f, c);
  }

  // image
  //

  image::
  image (const ::xml_schema::uri& anyURI)
  : ::xml_schema::uri (anyURI),
    size_ (::xml_schema::flags (), this)
  {
  }

  image::
  image (const image& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::uri (x, f, c),
    size_ (x.size_, f, this)
  {
  }

  image::
  image (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::uri (e, f | ::xml_schema::flags::base, c),
    size_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void image::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "size" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< size_type > r (
          size_traits::create (i, f, this));

        this->size (r);
        continue;
      }
    }
  }

  image* image::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new image (*this, f, c);
  }

  // tracks
  //

  tracks::
  tracks ()
  : ::xml_schema::type (),
    track_ (::xml_schema::flags (), this)
  {
  }

  tracks::
  tracks (const tracks& x,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    track_ (x.track_, f, this)
  {
  }

  tracks::
  tracks (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    track_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void tracks::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // track
      //
      if (n.name () == "track" && n.namespace_ () == "")
      {
        ::std::auto_ptr< track_type > r (
          track_traits::create (i, f, this));

        this->track ().push_back (r);
        continue;
      }

      break;
    }
  }

  tracks* tracks::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new tracks (*this, f, c);
  }

  // toptags
  //

  toptags::
  toptags ()
  : ::xml_schema::type (),
    tag_ (::xml_schema::flags (), this)
  {
  }

  toptags::
  toptags (const toptags& x,
           ::xml_schema::flags f,
           ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    tag_ (x.tag_, f, this)
  {
  }

  toptags::
  toptags (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    tag_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void toptags::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // tag
      //
      if (n.name () == "tag" && n.namespace_ () == "")
      {
        ::std::auto_ptr< tag_type > r (
          tag_traits::create (i, f, this));

        this->tag ().push_back (r);
        continue;
      }

      break;
    }
  }

  toptags* toptags::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new toptags (*this, f, c);
  }

  // wiki
  //

  wiki::
  wiki (const published_type& published,
        const summary_type& summary,
        const content_type& content)
  : ::xml_schema::type (),
    published_ (published, ::xml_schema::flags (), this),
    summary_ (summary, ::xml_schema::flags (), this),
    content_ (content, ::xml_schema::flags (), this)
  {
  }

  wiki::
  wiki (const wiki& x,
        ::xml_schema::flags f,
        ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    published_ (x.published_, f, this),
    summary_ (x.summary_, f, this),
    content_ (x.content_, f, this)
  {
  }

  wiki::
  wiki (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    published_ (f, this),
    summary_ (f, this),
    content_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void wiki::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // published
      //
      if (n.name () == "published" && n.namespace_ () == "")
      {
        ::std::auto_ptr< published_type > r (
          published_traits::create (i, f, this));

        if (!published_.present ())
        {
          this->published (r);
          continue;
        }
      }

      // summary
      //
      if (n.name () == "summary" && n.namespace_ () == "")
      {
        ::std::auto_ptr< summary_type > r (
          summary_traits::create (i, f, this));

        if (!summary_.present ())
        {
          this->summary (r);
          continue;
        }
      }

      // content
      //
      if (n.name () == "content" && n.namespace_ () == "")
      {
        ::std::auto_ptr< content_type > r (
          content_traits::create (i, f, this));

        if (!content_.present ())
        {
          this->content (r);
          continue;
        }
      }

      break;
    }

    if (!published_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "published",
        "");
    }

    if (!summary_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "summary",
        "");
    }

    if (!content_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "content",
        "");
    }
  }

  wiki* wiki::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new wiki (*this, f, c);
  }

  // track
  //

  track::
  track (const name_type& name,
         const duration_type& duration,
         const mbid_type& mbid,
         const url_type& url,
         const streamable_type& streamable,
         const artist_type& artist)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    duration_ (duration, ::xml_schema::flags (), this),
    mbid_ (mbid, ::xml_schema::flags (), this),
    url_ (url, ::xml_schema::flags (), this),
    streamable_ (streamable, ::xml_schema::flags (), this),
    artist_ (artist, ::xml_schema::flags (), this),
    rank_ (::xml_schema::flags (), this)
  {
  }

  track::
  track (const track& x,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    duration_ (x.duration_, f, this),
    mbid_ (x.mbid_, f, this),
    url_ (x.url_, f, this),
    streamable_ (x.streamable_, f, this),
    artist_ (x.artist_, f, this),
    rank_ (x.rank_, f, this)
  {
  }

  track::
  track (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    duration_ (f, this),
    mbid_ (f, this),
    url_ (f, this),
    streamable_ (f, this),
    artist_ (f, this),
    rank_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void track::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ () == "")
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // duration
      //
      if (n.name () == "duration" && n.namespace_ () == "")
      {
        if (!duration_.present ())
        {
          this->duration (duration_traits::create (i, f, this));
          continue;
        }
      }

      // mbid
      //
      if (n.name () == "mbid" && n.namespace_ () == "")
      {
        ::std::auto_ptr< mbid_type > r (
          mbid_traits::create (i, f, this));

        if (!mbid_.present ())
        {
          this->mbid (r);
          continue;
        }
      }

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      // streamable
      //
      if (n.name () == "streamable" && n.namespace_ () == "")
      {
        ::std::auto_ptr< streamable_type > r (
          streamable_traits::create (i, f, this));

        if (!streamable_.present ())
        {
          this->streamable (r);
          continue;
        }
      }

      // artist
      //
      if (n.name () == "artist" && n.namespace_ () == "")
      {
        ::std::auto_ptr< artist_type > r (
          artist_traits::create (i, f, this));

        if (!artist_.present ())
        {
          this->artist (r);
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    if (!duration_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "duration",
        "");
    }

    if (!mbid_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mbid",
        "");
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "");
    }

    if (!streamable_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "streamable",
        "");
    }

    if (!artist_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "artist",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "rank" && n.namespace_ ().empty ())
      {
        this->rank (rank_traits::create (i, f, this));
        continue;
      }
    }
  }

  track* track::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new track (*this, f, c);
  }

  // tag
  //

  tag::
  tag (const name_type& name,
       const url_type& url)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    url_ (url, ::xml_schema::flags (), this)
  {
  }

  tag::
  tag (const tag& x,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    url_ (x.url_, f, this)
  {
  }

  tag::
  tag (const ::xercesc::DOMElement& e,
       ::xml_schema::flags f,
       ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    url_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void tag::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ () == "")
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "");
    }
  }

  tag* tag::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new tag (*this, f, c);
  }

  // streamable
  //

  streamable::
  streamable (const ::xml_schema::byte& byte)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::byte, char, ::xml_schema::simple_type > (byte),
    fulltrack_ (::xml_schema::flags (), this)
  {
  }

  streamable::
  streamable (const streamable& x,
              ::xml_schema::flags f,
              ::xml_schema::type* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::byte, char, ::xml_schema::simple_type > (x, f, c),
    fulltrack_ (x.fulltrack_, f, this)
  {
  }

  streamable::
  streamable (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::type* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::byte, char, ::xml_schema::simple_type > (e, f | ::xml_schema::flags::base, c),
    fulltrack_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void streamable::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "fulltrack" && n.namespace_ ().empty ())
      {
        this->fulltrack (fulltrack_traits::create (i, f, this));
        continue;
      }
    }
  }

  streamable* streamable::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new streamable (*this, f, c);
  }

  // artist
  //

  artist::
  artist (const name_type& name,
          const mbid_type& mbid,
          const url_type& url)
  : ::xml_schema::type (),
    name_ (name, ::xml_schema::flags (), this),
    mbid_ (mbid, ::xml_schema::flags (), this),
    url_ (url, ::xml_schema::flags (), this)
  {
  }

  artist::
  artist (const artist& x,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (x, f, c),
    name_ (x.name_, f, this),
    mbid_ (x.mbid_, f, this),
    url_ (x.url_, f, this)
  {
  }

  artist::
  artist (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::type* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    name_ (f, this),
    mbid_ (f, this),
    url_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e);
      this->parse (p, f);
    }
  }

  void artist::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // name
      //
      if (n.name () == "name" && n.namespace_ () == "")
      {
        ::std::auto_ptr< name_type > r (
          name_traits::create (i, f, this));

        if (!name_.present ())
        {
          this->name (r);
          continue;
        }
      }

      // mbid
      //
      if (n.name () == "mbid" && n.namespace_ () == "")
      {
        ::std::auto_ptr< mbid_type > r (
          mbid_traits::create (i, f, this));

        if (!mbid_.present ())
        {
          this->mbid (r);
          continue;
        }
      }

      // url
      //
      if (n.name () == "url" && n.namespace_ () == "")
      {
        ::std::auto_ptr< url_type > r (
          url_traits::create (i, f, this));

        if (!url_.present ())
        {
          this->url (r);
          continue;
        }
      }

      break;
    }

    if (!name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "name",
        "");
    }

    if (!mbid_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "mbid",
        "");
    }

    if (!url_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "url",
        "");
    }
  }

  artist* artist::
  _clone (::xml_schema::flags f,
          ::xml_schema::type* c) const
  {
    return new artist (*this, f, c);
  }
}

#include <istream>
#include <xercesc/framework/Wrapper4InputSource.hpp>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace LastFMAlbumInfo
{
  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& u,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (u, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& sid,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    ::xercesc::Wrapper4InputSource wrap (&isrc, false);
    return ::LastFMAlbumInfo::lfm_ (wrap, h, f, p);
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xml_schema::error_handler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& i,
        ::xercesc::DOMErrorHandler& h,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (i, h, p, f));

    if (!d)
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
      ::LastFMAlbumInfo::lfm_ (
        d.get (), f | ::xml_schema::flags::own_dom, p));

    if (f & ::xml_schema::flags::keep_dom)
      d.release ();

    return r;
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMDocument& d,
        ::xml_schema::flags f,
        const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
        ::LastFMAlbumInfo::lfm_ (
          c.get (), f | ::xml_schema::flags::own_dom, p));

      c.release ();
      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "lfm" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
        ::xsd::cxx::tree::traits< ::LastFMAlbumInfo::lfm, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "lfm",
      "");
  }

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::xercesc::DOMDocument* d,
        ::xml_schema::flags f,
        const ::xml_schema::properties&)
  {
    ::xsd::cxx::xml::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    const ::xercesc::DOMElement& e (
      c.get ()
      ? *c->getDocumentElement ()
      : *d->getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "lfm" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::LastFMAlbumInfo::lfm > r (
        ::xsd::cxx::tree::traits< ::LastFMAlbumInfo::lfm, char >::create (
          e, f, 0));
      c.release ();
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "lfm",
      "");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

