// Copyright (C) 2005-2007 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef XSD_ALBUM_INFO_2_0_HXX
#define XSD_ALBUM_INFO_2_0_HXX

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/version.hxx>

#if (XSD_INT_VERSION != 3000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/tree/parsing.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type<type> simple_type;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef integer non_positive_integer;
  typedef integer non_negative_integer;
  typedef integer positive_integer;
  typedef integer negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken> nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< type, char, ncname > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::day< char, simple_type > day;
  typedef ::xsd::cxx::tree::month< char, simple_type > month;
  typedef ::xsd::cxx::tree::month_day< char, simple_type > month_day;
  typedef ::xsd::cxx::tree::year< char, simple_type > year;
  typedef ::xsd::cxx::tree::year_month< char, simple_type > year_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // DOM user data key for back pointers to tree nodes.
  //
#ifndef XSD_CXX_TREE_TREE_NODE_KEY_IN___XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY_IN___XML_SCHEMA

  const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;

#endif

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_type_info< char > no_type_info;
  typedef ::xsd::cxx::tree::not_derived< char > not_derived;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::serialization< char > serialization;
  typedef ::xsd::cxx::tree::no_namespace_mapping< char > no_namespace_mapping;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;
  typedef ::xsd::cxx::tree::xsi_already_in_use< char > xsi_already_in_use;
  typedef ::xsd::cxx::tree::bounds< char > bounds;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Error handler interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;
}

// Forward declarations.
//
namespace LastFMAlbumInfo
{
  class lfm;
  class album;
  class image;
  class tracks;
  class toptags;
  class wiki;
  class track;
  class tag;
  class streamable;
  class artist;
}


#include <memory>    // std::auto_ptr
#include <algorithm> // std::binary_search

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

namespace LastFMAlbumInfo
{
  class lfm: public ::xml_schema::type
  {
    public:
    // album
    // 
    typedef ::LastFMAlbumInfo::album album_type;
    typedef ::xsd::cxx::tree::traits< album_type, char > album_traits;

    const album_type&
    album () const;

    album_type&
    album ();

    void
    album (const album_type& x);

    void
    album (::std::auto_ptr< album_type > p);

    // status
    // 
    typedef ::xml_schema::string status_type;
    typedef ::xsd::cxx::tree::optional< status_type > status_optional;
    typedef ::xsd::cxx::tree::traits< status_type, char > status_traits;

    const status_optional&
    status () const;

    status_optional&
    status ();

    void
    status (const status_type& x);

    void
    status (const status_optional& x);

    void
    status (::std::auto_ptr< status_type > p);

    // Constructors.
    //
    lfm (const album_type&);

    lfm (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f = 0,
         ::xml_schema::type* c = 0);

    lfm (const lfm& x,
         ::xml_schema::flags f = 0,
         ::xml_schema::type* c = 0);

    virtual lfm*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< album_type > album_;
    status_optional status_;
  };

  class album: public ::xml_schema::type
  {
    public:
    // name
    // 
    typedef ::xml_schema::string name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::auto_ptr< name_type > p);

    // artist
    // 
    typedef ::xml_schema::string artist_type;
    typedef ::xsd::cxx::tree::traits< artist_type, char > artist_traits;

    const artist_type&
    artist () const;

    artist_type&
    artist ();

    void
    artist (const artist_type& x);

    void
    artist (::std::auto_ptr< artist_type > p);

    // id
    // 
    typedef ::xml_schema::int_ id_type;
    typedef ::xsd::cxx::tree::traits< id_type, char > id_traits;

    const id_type&
    id () const;

    id_type&
    id ();

    void
    id (const id_type& x);

    // mbid
    // 
    typedef ::xml_schema::string mbid_type;
    typedef ::xsd::cxx::tree::traits< mbid_type, char > mbid_traits;

    const mbid_type&
    mbid () const;

    mbid_type&
    mbid ();

    void
    mbid (const mbid_type& x);

    void
    mbid (::std::auto_ptr< mbid_type > p);

    // url
    // 
    typedef ::xml_schema::uri url_type;
    typedef ::xsd::cxx::tree::traits< url_type, char > url_traits;

    const url_type&
    url () const;

    url_type&
    url ();

    void
    url (const url_type& x);

    void
    url (::std::auto_ptr< url_type > p);

    // releasedate
    // 
    typedef ::xml_schema::string releasedate_type;
    typedef ::xsd::cxx::tree::traits< releasedate_type, char > releasedate_traits;

    const releasedate_type&
    releasedate () const;

    releasedate_type&
    releasedate ();

    void
    releasedate (const releasedate_type& x);

    void
    releasedate (::std::auto_ptr< releasedate_type > p);

    // image
    // 
    typedef ::LastFMAlbumInfo::image image_type;
    typedef ::xsd::cxx::tree::sequence< image_type > image_sequence;
    typedef image_sequence::iterator image_iterator;
    typedef image_sequence::const_iterator image_const_iterator;
    typedef ::xsd::cxx::tree::traits< image_type, char > image_traits;

    const image_sequence&
    image () const;

    image_sequence&
    image ();

    void
    image (const image_sequence& s);

    // listeners
    // 
    typedef ::xml_schema::int_ listeners_type;
    typedef ::xsd::cxx::tree::traits< listeners_type, char > listeners_traits;

    const listeners_type&
    listeners () const;

    listeners_type&
    listeners ();

    void
    listeners (const listeners_type& x);

    // playcount
    // 
    typedef ::xml_schema::int_ playcount_type;
    typedef ::xsd::cxx::tree::traits< playcount_type, char > playcount_traits;

    const playcount_type&
    playcount () const;

    playcount_type&
    playcount ();

    void
    playcount (const playcount_type& x);

    // tracks
    // 
    typedef ::LastFMAlbumInfo::tracks tracks_type;
    typedef ::xsd::cxx::tree::traits< tracks_type, char > tracks_traits;

    const tracks_type&
    tracks () const;

    tracks_type&
    tracks ();

    void
    tracks (const tracks_type& x);

    void
    tracks (::std::auto_ptr< tracks_type > p);

    // toptags
    // 
    typedef ::LastFMAlbumInfo::toptags toptags_type;
    typedef ::xsd::cxx::tree::traits< toptags_type, char > toptags_traits;

    const toptags_type&
    toptags () const;

    toptags_type&
    toptags ();

    void
    toptags (const toptags_type& x);

    void
    toptags (::std::auto_ptr< toptags_type > p);

    // wiki
    // 
    typedef ::LastFMAlbumInfo::wiki wiki_type;
    typedef ::xsd::cxx::tree::traits< wiki_type, char > wiki_traits;

    const wiki_type&
    wiki () const;

    wiki_type&
    wiki ();

    void
    wiki (const wiki_type& x);

    void
    wiki (::std::auto_ptr< wiki_type > p);

    // Constructors.
    //
    album (const name_type&,
           const artist_type&,
           const id_type&,
           const mbid_type&,
           const url_type&,
           const releasedate_type&,
           const listeners_type&,
           const playcount_type&,
           const tracks_type&,
           const toptags_type&,
           const wiki_type&);

    album (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    album (const album& x,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    virtual album*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< name_type > name_;
    ::xsd::cxx::tree::one< artist_type > artist_;
    ::xsd::cxx::tree::one< id_type > id_;
    ::xsd::cxx::tree::one< mbid_type > mbid_;
    ::xsd::cxx::tree::one< url_type > url_;
    ::xsd::cxx::tree::one< releasedate_type > releasedate_;
    image_sequence image_;
    ::xsd::cxx::tree::one< listeners_type > listeners_;
    ::xsd::cxx::tree::one< playcount_type > playcount_;
    ::xsd::cxx::tree::one< tracks_type > tracks_;
    ::xsd::cxx::tree::one< toptags_type > toptags_;
    ::xsd::cxx::tree::one< wiki_type > wiki_;
  };

  class image: public ::xml_schema::uri
  {
    public:
    // size
    // 
    typedef ::xml_schema::string size_type;
    typedef ::xsd::cxx::tree::optional< size_type > size_optional;
    typedef ::xsd::cxx::tree::traits< size_type, char > size_traits;

    const size_optional&
    size () const;

    size_optional&
    size ();

    void
    size (const size_type& x);

    void
    size (const size_optional& x);

    void
    size (::std::auto_ptr< size_type > p);

    // Constructors.
    //
    image (const ::xml_schema::uri&);

    image (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    image (const image& x,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    virtual image*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    size_optional size_;
  };

  class tracks: public ::xml_schema::type
  {
    public:
    // track
    // 
    typedef ::LastFMAlbumInfo::track track_type;
    typedef ::xsd::cxx::tree::sequence< track_type > track_sequence;
    typedef track_sequence::iterator track_iterator;
    typedef track_sequence::const_iterator track_const_iterator;
    typedef ::xsd::cxx::tree::traits< track_type, char > track_traits;

    const track_sequence&
    track () const;

    track_sequence&
    track ();

    void
    track (const track_sequence& s);

    // Constructors.
    //
    tracks ();

    tracks (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0);

    tracks (const tracks& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0);

    virtual tracks*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    track_sequence track_;
  };

  class toptags: public ::xml_schema::type
  {
    public:
    // tag
    // 
    typedef ::LastFMAlbumInfo::tag tag_type;
    typedef ::xsd::cxx::tree::sequence< tag_type > tag_sequence;
    typedef tag_sequence::iterator tag_iterator;
    typedef tag_sequence::const_iterator tag_const_iterator;
    typedef ::xsd::cxx::tree::traits< tag_type, char > tag_traits;

    const tag_sequence&
    tag () const;

    tag_sequence&
    tag ();

    void
    tag (const tag_sequence& s);

    // Constructors.
    //
    toptags ();

    toptags (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f = 0,
             ::xml_schema::type* c = 0);

    toptags (const toptags& x,
             ::xml_schema::flags f = 0,
             ::xml_schema::type* c = 0);

    virtual toptags*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    tag_sequence tag_;
  };

  class wiki: public ::xml_schema::type
  {
    public:
    // published
    // 
    typedef ::xml_schema::string published_type;
    typedef ::xsd::cxx::tree::traits< published_type, char > published_traits;

    const published_type&
    published () const;

    published_type&
    published ();

    void
    published (const published_type& x);

    void
    published (::std::auto_ptr< published_type > p);

    // summary
    // 
    typedef ::xml_schema::string summary_type;
    typedef ::xsd::cxx::tree::traits< summary_type, char > summary_traits;

    const summary_type&
    summary () const;

    summary_type&
    summary ();

    void
    summary (const summary_type& x);

    void
    summary (::std::auto_ptr< summary_type > p);

    // content
    // 
    typedef ::xml_schema::string content_type;
    typedef ::xsd::cxx::tree::traits< content_type, char > content_traits;

    const content_type&
    content () const;

    content_type&
    content ();

    void
    content (const content_type& x);

    void
    content (::std::auto_ptr< content_type > p);

    // Constructors.
    //
    wiki (const published_type&,
          const summary_type&,
          const content_type&);

    wiki (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f = 0,
          ::xml_schema::type* c = 0);

    wiki (const wiki& x,
          ::xml_schema::flags f = 0,
          ::xml_schema::type* c = 0);

    virtual wiki*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< published_type > published_;
    ::xsd::cxx::tree::one< summary_type > summary_;
    ::xsd::cxx::tree::one< content_type > content_;
  };

  class track: public ::xml_schema::type
  {
    public:
    // name
    // 
    typedef ::xml_schema::string name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::auto_ptr< name_type > p);

    // duration
    // 
    typedef ::xml_schema::int_ duration_type;
    typedef ::xsd::cxx::tree::traits< duration_type, char > duration_traits;

    const duration_type&
    duration () const;

    duration_type&
    duration ();

    void
    duration (const duration_type& x);

    // mbid
    // 
    typedef ::xml_schema::string mbid_type;
    typedef ::xsd::cxx::tree::traits< mbid_type, char > mbid_traits;

    const mbid_type&
    mbid () const;

    mbid_type&
    mbid ();

    void
    mbid (const mbid_type& x);

    void
    mbid (::std::auto_ptr< mbid_type > p);

    // url
    // 
    typedef ::xml_schema::uri url_type;
    typedef ::xsd::cxx::tree::traits< url_type, char > url_traits;

    const url_type&
    url () const;

    url_type&
    url ();

    void
    url (const url_type& x);

    void
    url (::std::auto_ptr< url_type > p);

    // streamable
    // 
    typedef ::LastFMAlbumInfo::streamable streamable_type;
    typedef ::xsd::cxx::tree::traits< streamable_type, char > streamable_traits;

    const streamable_type&
    streamable () const;

    streamable_type&
    streamable ();

    void
    streamable (const streamable_type& x);

    void
    streamable (::std::auto_ptr< streamable_type > p);

    // artist
    // 
    typedef ::LastFMAlbumInfo::artist artist_type;
    typedef ::xsd::cxx::tree::traits< artist_type, char > artist_traits;

    const artist_type&
    artist () const;

    artist_type&
    artist ();

    void
    artist (const artist_type& x);

    void
    artist (::std::auto_ptr< artist_type > p);

    // rank
    // 
    typedef ::xml_schema::byte rank_type;
    typedef ::xsd::cxx::tree::optional< rank_type > rank_optional;
    typedef ::xsd::cxx::tree::traits< rank_type, char > rank_traits;

    const rank_optional&
    rank () const;

    rank_optional&
    rank ();

    void
    rank (const rank_type& x);

    void
    rank (const rank_optional& x);

    // Constructors.
    //
    track (const name_type&,
           const duration_type&,
           const mbid_type&,
           const url_type&,
           const streamable_type&,
           const artist_type&);

    track (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    track (const track& x,
           ::xml_schema::flags f = 0,
           ::xml_schema::type* c = 0);

    virtual track*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< name_type > name_;
    ::xsd::cxx::tree::one< duration_type > duration_;
    ::xsd::cxx::tree::one< mbid_type > mbid_;
    ::xsd::cxx::tree::one< url_type > url_;
    ::xsd::cxx::tree::one< streamable_type > streamable_;
    ::xsd::cxx::tree::one< artist_type > artist_;
    rank_optional rank_;
  };

  class tag: public ::xml_schema::type
  {
    public:
    // name
    // 
    typedef ::xml_schema::string name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::auto_ptr< name_type > p);

    // url
    // 
    typedef ::xml_schema::uri url_type;
    typedef ::xsd::cxx::tree::traits< url_type, char > url_traits;

    const url_type&
    url () const;

    url_type&
    url ();

    void
    url (const url_type& x);

    void
    url (::std::auto_ptr< url_type > p);

    // Constructors.
    //
    tag (const name_type&,
         const url_type&);

    tag (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f = 0,
         ::xml_schema::type* c = 0);

    tag (const tag& x,
         ::xml_schema::flags f = 0,
         ::xml_schema::type* c = 0);

    virtual tag*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< name_type > name_;
    ::xsd::cxx::tree::one< url_type > url_;
  };

  class streamable: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::byte, char, ::xml_schema::simple_type >
  {
    public:
    // fulltrack
    // 
    typedef ::xml_schema::byte fulltrack_type;
    typedef ::xsd::cxx::tree::optional< fulltrack_type > fulltrack_optional;
    typedef ::xsd::cxx::tree::traits< fulltrack_type, char > fulltrack_traits;

    const fulltrack_optional&
    fulltrack () const;

    fulltrack_optional&
    fulltrack ();

    void
    fulltrack (const fulltrack_type& x);

    void
    fulltrack (const fulltrack_optional& x);

    // Constructors.
    //
    streamable (const ::xml_schema::byte&);

    streamable (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::type* c = 0);

    streamable (const streamable& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::type* c = 0);

    virtual streamable*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    fulltrack_optional fulltrack_;
  };

  class artist: public ::xml_schema::type
  {
    public:
    // name
    // 
    typedef ::xml_schema::string name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::auto_ptr< name_type > p);

    // mbid
    // 
    typedef ::xml_schema::string mbid_type;
    typedef ::xsd::cxx::tree::traits< mbid_type, char > mbid_traits;

    const mbid_type&
    mbid () const;

    mbid_type&
    mbid ();

    void
    mbid (const mbid_type& x);

    void
    mbid (::std::auto_ptr< mbid_type > p);

    // url
    // 
    typedef ::xml_schema::uri url_type;
    typedef ::xsd::cxx::tree::traits< url_type, char > url_traits;

    const url_type&
    url () const;

    url_type&
    url ();

    void
    url (const url_type& x);

    void
    url (::std::auto_ptr< url_type > p);

    // Constructors.
    //
    artist (const name_type&,
            const mbid_type&,
            const url_type&);

    artist (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0);

    artist (const artist& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0);

    virtual artist*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::type* c = 0) const;

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    private:
    ::xsd::cxx::tree::one< name_type > name_;
    ::xsd::cxx::tree::one< mbid_type > mbid_;
    ::xsd::cxx::tree::one< url_type > url_;
  };
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMInputSource.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace LastFMAlbumInfo
{
  // Parse a URI or a local file.
  //

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& uri,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& uri,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::std::string& uri,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse std::istream.
  //

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& id,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& id,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::std::istream& is,
        const ::std::string& id,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse xercesc::DOMInputSource.
  //

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& is,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& is,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMInputSource& is,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse xercesc::DOMDocument.
  //

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (const ::xercesc::DOMDocument& d,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::auto_ptr< ::LastFMAlbumInfo::lfm >
  lfm_ (::xercesc::DOMDocument* d,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // XSD_ALBUM_INFO_2_0_HXX
