FIND_PATH(XERCESC_INCLUDE_DIR xercesc
  HINTS $ENV{XERCESCDIR}
)
MARK_AS_ADVANCED(XERCESC_INCLUDE_DIR)
 
FIND_LIBRARY(XERCESC_LIBRARY xerces-c
  HINTS $ENV{XERCESDIR}
)
MARK_AS_ADVANCED(XERCESC_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(XercesC DEFAULT_MSG XERCESC_LIBRARY XERCESC_INCLUDE_DIR)
