FIND_PATH(SIDPLAY_INCLUDE_DIR sidplay
  HINTS $ENV{SIDPLAYDIR}
)
MARK_AS_ADVANCED(SIDPLAY_INCLUDE_DIR)
 
FIND_LIBRARY(SIDPLAY_LIBRARY sidplay
  HINTS $ENV{SIDPLAYDIR}
)
MARK_AS_ADVANCED(SIDPLAY_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SIDPLAY DEFAULT_MSG SIDPLAY_LIBRARY SIDPLAY_INCLUDE_DIR)
