FIND_PATH(CDPARANOIA_INCLUDE_DIR cdda_interface.h
  HINTS $ENV{CDPARANOIA_PREFIX}
)
MARK_AS_ADVANCED(CDPARANOIA_INCLUDE_DIR)

IF(NOT CDPARANOID_INCLUDE_DIR)
  FIND_PATH(CDPARANOIA_INCLUDE_DIR cdda/cdda_interface.h
    HINTS $ENV{CDPARANOIA_PREFIX}
  )
  IF(CDPARANOID_INCLUDE_DIR)
    SET(CDPARANOID_INCLUDE_DIR "${CDPARANOID_INCLUDE_DIR}/cdda")
  ENDIF(CDPARANOID_INCLUDE_DIR)
ENDIF(NOT CDPARANOID_INCLUDE_DIR)

FIND_LIBRARY(CDPARANOIA_LIBRARY cdda_interface
  HINTS $ENV{CDPARANOIA_PREFIX}
)
MARK_AS_ADVANCED(CDPARANOIA_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CDPARANOIA DEFAULT_MSG CDPARANOIA_LIBRARY CDPARANOIA_INCLUDE_DIR)
